### ISSUE TITLE
Access parent element in loop with same name as child element

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [cbroglie/mustache#41]
Given the following YAML:

```
---
name: cashew
data: hello
projects:
  - name: mustache
  - name: pystache
```

And the following Mustache:
```
Parent Name: {{name}}
{{data}}
{{#projects}}
    Top Child Data: {{data}}
    Parent Name: {{#.}}{{name}}{{/.}}
    Child Name: {{name}}
{{/projects}}
```
I am getting the following output:
```
Parent Name: cashew
hello
    Top Child Data: hello
    Parent Name: mustache
    Child Name: mustache
    Top Child Data: hello
    Parent Name: pystache
    Child Name: pystache
```
How can I access the top level object element from within the loop with the same name as a child's element?
